# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_qvd_cpp <- function(path, prefer_numeric_duals = TRUE, include_indices = FALSE) {
    .Call(`_qvdr_read_qvd_cpp`, path, prefer_numeric_duals, include_indices)
}

